# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "GPloadPackage"
client_id = "YOUR_CLIENT_ID"
application_url = "https://ecomlatam-production.up.railway.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "YOUR_DEV_STORE.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,write_fulfillments,read_products,write_products"

[auth]
redirect_urls = [
  "https://ecomlatam-production.up.railway.app/api/shopify/callback"
]

[webhooks]
api_version = "2025-10"

# GDPR Mandatory Compliance Webhooks
# These are required by Shopify for app submission
[[webhooks.subscriptions]]
topics = ["customers/data_request"]
uri = "/api/shopify/webhooks/customers-data_request"

[[webhooks.subscriptions]]
topics = ["customers/redact"]
uri = "/api/shopify/webhooks/customers-redact"

[[webhooks.subscriptions]]
topics = ["shop/redact"]
uri = "/api/shopify/webhooks/shop-redact"

# Business Logic Webhooks
[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "/api/shopify/webhooks/orders-create"

[[webhooks.subscriptions]]
topics = ["orders/cancelled"]
uri = "/api/shopify/webhooks/orders-cancelled"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/shopify/webhooks/app-uninstalled"

[pos]
embedded = false
